// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT6GnOB6Zkh-vyerwRLPFUzUQFHn_Uq5g',
    appId: '1:169309664734:web:6c4b5149bf2edcf627994f',
    messagingSenderId: '169309664734',
    projectId: 'product-catalog-1d82d',
    authDomain: 'product-catalog-1d82d.firebaseapp.com',
    storageBucket: 'product-catalog-1d82d.appspot.com',
    measurementId: 'G-H0XNFY7670',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCydl59b-jQn4jjaVWVJUQToLh0yuLwZcU',
    appId: '1:169309664734:android:12cf035257fff1a427994f',
    messagingSenderId: '169309664734',
    projectId: 'product-catalog-1d82d',
    storageBucket: 'product-catalog-1d82d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT6GnOB6Zkh-vyerwRLPFUzUQFHn_Uq5g',
    appId: '1:169309664734:web:435269aead05070a27994f',
    messagingSenderId: '169309664734',
    projectId: 'product-catalog-1d82d',
    authDomain: 'product-catalog-1d82d.firebaseapp.com',
    storageBucket: 'product-catalog-1d82d.appspot.com',
    measurementId: 'G-PGG3WBZWFZ',
  );
}
